#! /usr/bin/env php

<?php

use Commands\CodeIgniterInstall;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('CodeIgniter Install: Install the Latest Codeigniter Framework', '1.0');

$app->add(new CodeIgniterInstall(new GuzzleHttp\Client));

$app->run();